import { Injectable } from '@angular/core';
import { ApiMethod, AuthEndPoints } from 'src/app/core/constant/api-constant';
import { HttpService } from 'src/app/core/service/http/http.service';

export interface Purchase {
  purchaseId?: number; // Optional for adding, usually generated by DB
  purchaseDate: Date | null; // Send as Date object or ISO string, check backend expectation
  transactionTypeId: number;
  weight: number;
  rate: number;        // Added rate based on form changes
  amount: number;
  amountPaid: number;
  discountAmt: number;    // Check if null is allowed by backend, handle default if not
  balanceAmount: number;
  comments: string | null;
  updatedBy: number;      // Often set by backend
  userClientRoleId:number;
  updatedDt: Date | null; // Optional for adding, usually set by backend
}

@Injectable({
  providedIn: 'root'
})
export class PurchaseService {

  constructor(private httpService: HttpService) { }

  getPurchaseInfoByDate(purchaseDate: Date) {
    return this.httpService.requestCall(
      ApiMethod.POST, 
      AuthEndPoints.PURCHASE_INFO_BY_DATE,
      purchaseDate
    );
  }

  getAllUsersDetails() {
    return this.httpService.requestCall(
      ApiMethod.GET,
      AuthEndPoints.USER_MGMT
    );
  }

  addPurchase(purchase: Purchase) {
      console.log("Sending Purchase to API:", purchase); // Log payload before sending
      return this.httpService.requestCall(
        ApiMethod.POST,
        AuthEndPoints.ADD_PURCHASE,
        purchase // Send the purchase object as the body
      );
    }

    updatePurchase(purchase: Purchase) {
        return this.httpService.requestCall(
          ApiMethod.PUT,
          AuthEndPoints.UPDATE_PURCHASE,
          purchase // Send the purchase object as the body
       );
     } 

    deletePurchase(purchaseId: number) {
    console.log("Deleting Sales with ID:", purchaseId);
    return this.httpService.requestCall(
      ApiMethod.DELETE,
      AuthEndPoints.DELETE_PURCHASE,
      {},
      `?purchaseId=${purchaseId}`
    );
  }
}
