import { Injectable } from '@angular/core';
import { ApiMethod, AuthEndPoints } from 'src/app/core/constant/api-constant';
import { HttpService } from 'src/app/core/service/http/http.service';


export interface Sales {
  salesId?: number; // Optional for adding, usually generated by DB
  saleDate: Date | null; // Send as Date object or ISO string, check backend expectation
  transactionTypeId: number;
  cages: number; // Added cages as it's in the form
  fullCage: number;
  emptyCage: number;
  weight: number;
  rate: number;        // Added rate based on form changes
  amount: number;
  amountPaid: number;
  dressingAmount: number; // Check if null is allowed by backend, handle default if not
  discountAmt: number;    // Check if null is allowed by backend, handle default if not
  billNumber: string | null;
  balanceAmount: number;
  comments: string | null;
  updatedBy: number;      // Often set by backend
  smsFlag: boolean;
  userClientRoleId:number;
}

@Injectable({
  providedIn: 'root'
})
export class SalesService {

constructor(private httpService: HttpService) { }

  getSalesInfo() {
    // This endpoint seems unused in the component logic currently presented
    return this.httpService.requestCall(
      ApiMethod.GET,
      AuthEndPoints.SALES_INFO
    );
  }

  getSalesInfoByDate(saleDate: Date) {
    return this.httpService.requestCall(
      ApiMethod.POST, 
      AuthEndPoints.SALES_BY_DATE,
      saleDate
    );
  }

  addSales(sales: Sales) {
    console.log("Sending Sales to API:", sales); // Log payload before sending
    return this.httpService.requestCall(
      ApiMethod.POST,
      AuthEndPoints.ADD_SALES,
      sales // Send the sales object as the body
    );
  }

  updateSales(sales: Sales) {
    console.log("Sending Sales to API:", sales); // Log payload before sending
    return this.httpService.requestCall(
      ApiMethod.PUT,
      AuthEndPoints.UPDATE_SALES,
      sales // Send the sales object as the body
    );
  }  
  
  deleteSales(salesId: number) {
    console.log("Deleting Sales with ID:", salesId);
    return this.httpService.requestCall(
      ApiMethod.DELETE,
      AuthEndPoints.DELETE_SALES,
      {},
      `?saleId=${salesId}`
    );
  }

  getAllUsersDetails() {
    return this.httpService.requestCall(
      ApiMethod.GET,
      AuthEndPoints.USER_MGMT
    );
  }

  getLiveRate(saleDate: Date) {
    return this.httpService.requestCall(
      ApiMethod.POST,
      AuthEndPoints.GET_LIVERATE_INFO,
      saleDate
    );
  }

  sendWhatsAppMessages(date: string) {
    console.log("Sending WhatsApp message for date:", date); // Log payload before sending
  return this.httpService.requestCall(
    ApiMethod.POST,
    AuthEndPoints.WHATSAPP_MESSAGE,
    {date:date}
  );
  }

}