export enum ApiMethod {
    GET = 'get',
    POST = 'post',
    PUT = 'put',
    DELETE = 'delete',
    PATCH = 'patch'
  }
  export enum AuthEndPoints {
    LOGIN = 'User/AuthenticateUser',
    DASHBOARD_DETAILS = 'DashBoard/GetDashBoard',
    GET_STUDENT_DETAILS_BYID = 'TaStudentdetails/GetStudentDataByID?id=',
    SALES_INFO  = 'Sales/GetSales',
    PURCHASE_INFO  = 'Purchase/GetPurchases',
    CUSTOMER_INFO  = 'Report/GetCustomerList',
    VENDOR_INFO  = 'Report/GetAllVendor',
    SALES_REPORT = 'Report/GetSalesReport',
    SALES_PAYMENT_REPORT = 'Report/GetSalesReport',
    SMS_REPORT = 'Report/GetSMSReport',
    PURCHASE_REPORT = 'Report/GetPurchaseReport',
    PURCHASE_PAYMENT_REPORT = 'Report/GetPurchaseReport',
    USER_MGMT = 'User/GetAllUsers',
    USER_MGMT_ADD = 'User/AddUser',
    USER_MGMT_UPDATE = 'User/EditUser',
    USER_MGMT_TOGGLE_STATUS = 'User/DeleteUser',
    GET_RATE_INFO = 'Rate/GetDefaultRates',
    ADD_RATE_INFO = 'Rate/AddRates',
    SALES_BY_DATE  = 'Sales/GetSalesByDate',
    ADD_SALES = 'Sales/AddSales',
    UPDATE_SALES = 'Sales/UpdateSales',
    GET_LIVERATE_INFO = 'Rate/GetLiveRateByDate',
    PURCHASE_INFO_BY_DATE = 'Purchase/GetPurchaseByDate',
    ADD_PURCHASE = 'Purchase/AddPurchase',
    UPDATE_PURCHASE = 'Purchase/UpdatePurchase',
    WHATSAPP_MESSAGE = 'WhatsApp/sendWhatsAppMessages',
    REGISTER_USER_MGMT = 'User/RegisterUser',
    SET_PASSWORD = 'User/SetInitialPassword',
    DELETE_SALES = 'Sales/DeleteSales',
    DELETE_PURCHASE = 'Purchase/DeletePurchase',
    SALESAPPROVAL_BY_DATE = 'SalesApproval/GetSalesApprovalByDate',
    DELETE_SALES_APPROVAL = 'SalesApproval/DeleteApproval',
    ADD_SALES_APPROVAL = 'SalesApproval/AddSalesApprovals',
    UPDATE_SALES_APPROVAL = 'SalesApproval/UpdateSalesApprovals',
  }
